### ISSUE TITLE
fastapi接口中 /voice 接口当 language = auto时报错

### ISSUE THREAD

**Issue by sucat1997** [jiangyuxiaoxiao/Bert-VITS2-UI#10]
错误定位在：
        audios = []
        with torch.no_grad(): 下面，其中2.3新增的auto模式需要新的audio读取方式
![72c8cef6c4441ba5f8b4339d33704063](https://github.com/jiangyuxiaoxiao/Bert-VITS2-UI/assets/45302883/3c7c45cd-e669-4f37-b861-20b6055f1479)
![0d7a87c3be2aaf01eebb3ff7546542f6](https://github.com/jiangyuxiaoxiao/Bert-VITS2-UI/assets/45302883/db71b508-1cef-498e-8547-d5b4c9fc3052)

**Comment by sucat1997** [comment]
错误信息：
01-12 04:38:06 INFO     | hiyoriUI.py:412 | 127.0.0.1:63866/voice  text=你好&model_id=0&speaker_name=纳西妲&sdp_ratio=0.2&noise=0.2&noisew=0.9&length=1&language=auto&auto_translate=false&auto_split=false&style_weight=0.7
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\venv\lib\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "hiyoriUI.py", line 415, in voice
    return await _voice(
  File "hiyoriUI.py", line 320, in _voice
    infer(
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\infer.py", line 267, in infer
    bert, ja_bert, en_bert, phones, tones, lang_ids = get_text(
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\infer.py", line 109, in get_text
    norm_text, phone, tone, word2ph = clean_text(text, language_str)
  File "E:\Ai_bert-vits2 collection\HiyoriUI-0.8.0\Bert-VITS2\text\cleaner.py", line 8, in clean_text
    language_module = language_module_map[language]
KeyError: 'auto'

**Comment by sucat1997** [comment]
![cb829bdbbde19765f220d3d9ae24a428](https://github.com/jiangyuxiaoxiao/Bert-VITS2-UI/assets/45302883/49e710e0-79e8-4081-8fb9-81402522bd0a)

**Comment by jiangyuxiaoxiao** [comment]
2.3新增的是`AUTO`，参考`HiyoriUI`网页

**Comment by sucat1997** [comment]
AUTO可以用
